import Provider from "@/components/Provider"
import TopBar from "@/components/TopBar"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Provider>
          <TopBar />
           {children}
        </Provider>   
      </body>
    </html>
  )
}
